Variable view rewrite
helxplatform/helx-ui pull request #311
Opened 2024-07-22 22:34 UTC by frostyfan109

- Rewrite/cleanup variable view w/context so that we can support filters and other features that weren't otherwise feasible
- Add infinite scroll to variable view
- Fix study data source (e.g., HEAL studies vs Non-HEAL studies) coloring
- Group by study/collapse into variable list
- Add filters:
  - Subsearch filter
  - Data source filtering
  - Sort by score/data source, with ascending/descending options

2024-07-25 11:59 UTC, joshua-seals commented
RUN npm clean-install is causing the builds to fail, just fyi

2024-08-01 04:46 UTC, gaurav commented
I can't review the many code changes in this PR, but the end results look great! Some thoughts:
1. I think the subsearch filter is a bit too fuzzy: I tried filtering with "heart" and ended up matching a ton of "healing"s and one "part". But I LOVE that the substring search includes the variable source! So I think you're definitely heading in the right direction here.
2. I would personally have "Group by study" be the default, but I'm very curious what other Dug folks think -- I wonder if we could get you to demo this PR at one of our Tuesday 3pm meetings or at another time? I think we could get a lot of useful feedback on the UI that way.
3. Ideally the counts in the boxes (e.g. "HEAL Studies (4)") should change when you change the histogram -- but maybe that's too complicated? I like how the text above it changes from "Showing X of Y variables" to "Showing X of Y studies" when you turn on "Group by study" mode -- maybe the box could also change from "HEAL Studies (4 studies)" to "HEAL Studies (10 variables)" or something?
4. These results will be a lot more readable if we were to include the form/module name in these search results or if we had a study page to link to, but we don't have either yet :( But someday!

2024-08-01 19:16 UTC, frostyfan109 commented
> `RUN npm clean-install `is causing the builds to fail, just fyi, is this a custom command or do you mean `RUN npm ci`

npm ci is just an alias of clean-install as far as I know. I think we just need to rebuild the package lock

2024-08-01 19:51 UTC, frostyfan109 commented
Regarding fuzziness, we were by default using 1 LD if < 5 chars, otherwise 2 LD. I've fixed it to use 1 edit distance (LD) regardless of term length.

2024-08-26 22:32 UTC, hina-shah requested changes

2024-08-26 22:32 UTC, hina-shah commented on src/components/search/results/variable-view-layout/variable-view-layout.js
> +import { VariableSearchResults2 } from './variable-results-new'
Can we replace this with VariableSearchResults? Basically cleanup so that we don't have two files for variable-results.

2024-08-26 22:32 UTC, hina-shah commented on src/components/search/results/variable-view-layout/variable-view-layout.js
> +                    <VariableSearchResults2 />
Replace with VariableSearchResults

2024-08-26 22:32 UTC, hina-shah commented on src/components/search/results/variable-view-layout/variable-results-new.tsx
> +export const VariableSearchResults2 = () => {
Replace this with VariableSearchResults

2024-08-26 22:32 UTC, hina-shah commented on src/components/search/results/variable-view-layout/variable-results-new.tsx
This file is too big for my liking. Is it possible to split into a few files? There seem to be study related components, and variable related components. Maybe split them up? and export the VariableSearchResults with relevant things.?

2024-08-26 22:33 UTC, hina-shah commented
Thanks for all the work @frostyfan109 ! A few cleanup things, but other than that I think we should be okay.

2024-08-26 22:35 UTC, hina-shah commented
> 
> (3) That's an oversight on my part, I'll change it so the counts reflect the amounts actually being displayed.
Was this implemented?

2024-08-26 22:47 UTC, frostyfan109 commented on src/components/search/results/variable-view-layout/variable-results-new.tsx
will do, I didn't really clean up this branch at all so thanks for catching

2024-08-26 22:48 UTC, frostyfan109 commented
> > (3) That's an oversight on my part, I'll change it so the counts reflect the amounts actually being displayed.
> > Was this implemented?

I'm not sure, but I don't see it mentioned in newer commits so probably not. I'll check

2024-09-19 23:36 UTC, frostyfan109 commented
@hina-shah can you approve?

2024-09-20 12:02 UTC, hina-shah approved these changes

2024-10-01 14:33 UTC, merged